[project]
name = 'zerlin'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fee-oracle-v1]
path = 'contracts/fee-oracle.clar'
clarity_version = 4
epoch = 'latest'

[contracts.smart-alerts-v1]
path = 'contracts/smart-alerts.clar'
clarity_version = 4
epoch = 'latest'

[contracts.tx-templates-v1]
path = 'contracts/tx-templates.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lint_groups]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
